import { BadgeCheck, ExternalLink, FlaskConical, Globe, Sparkles } from "@/components/ui/icons";
import { cn } from "@/lib/cn";
import type { OptionSource, PlanOption } from "@/lib/types";

/**
 * Where a result came from, and what that means for trusting its price.
 *
 * This is the honest core of the dual-source design: an Atlas fare the booking
 * API will hold and a number an agent read on an aggregator page are different
 * kinds of claim. Showing them with the same styling would be misleading, so
 * each source gets its own label, colour and tooltip — and a crawled option
 * always exposes the page it came from.
 */

type SourceMeta = {
  label: string;
  tone: string;
  icon: typeof Globe;
  title: string;
};

const SOURCES: Record<OptionSource, SourceMeta> = {
  atlas: {
    label: "Atlas",
    tone: "text-[var(--success)] bg-[color-mix(in_srgb,var(--success)_14%,transparent)]",
    icon: BadgeCheck,
    title: "Live Atlas inventory — bookable through the booking API",
  },
  amadeus: {
    label: "Amadeus",
    tone: "text-[var(--info)] bg-[color-mix(in_srgb,var(--info)_14%,transparent)]",
    icon: Globe,
    title: "Amadeus test inventory — indicative pricing, not bookable here",
  },
  camofox: {
    label: "Research",
    tone: "text-[var(--warning)] bg-[color-mix(in_srgb,var(--warning)_16%,transparent)]",
    icon: Globe,
    title:
      "Advertised on a public page the browser agent read — not a held fare. Open the source to confirm.",
  },
  research: {
    label: "Research",
    tone: "text-[var(--warning)] bg-[color-mix(in_srgb,var(--warning)_16%,transparent)]",
    icon: Globe,
    title: "Derived from public web research",
  },
  llm: {
    label: "Simulated",
    tone: "text-[var(--muted)] bg-[color-mix(in_srgb,var(--muted)_14%,transparent)]",
    icon: Sparkles,
    title:
      "Generated by the model because no live source answered — realistic, but not a real fare",
  },
  mock: {
    label: "Placeholder",
    tone: "text-[var(--muted)] bg-[color-mix(in_srgb,var(--muted)_14%,transparent)]",
    icon: FlaskConical,
    title: "Placeholder data — configure a provider in the API Vault",
  },
};

export function SourceBadge({
  source,
  className,
}: {
  source: OptionSource | null;
  className?: string;
}) {
  if (!source) return null;
  const meta = SOURCES[source];
  if (!meta) return null;
  const Icon = meta.icon;

  return (
    <span
      title={meta.title}
      className={cn(
        "inline-flex shrink-0 items-center gap-1 rounded-[var(--r-pill)]",
        "px-2 py-0.5 text-[0.6rem] font-semibold uppercase tracking-wide",
        meta.tone,
        className,
      )}
    >
      <Icon className="h-3 w-3" />
      {meta.label}
    </span>
  );
}

/**
 * The trust row for one option: source, whether a booking API confirmed the
 * price, and the citation link when the number came from a page.
 */
export function SourceTrustRow({ option }: { option: PlanOption }) {
  return (
    <div className="flex flex-wrap items-center gap-1.5">
      <SourceBadge source={option.source} />

      {option.verified ? (
        <span
          title="Re-priced and confirmed by the booking API"
          className="inline-flex items-center gap-1 rounded-[var(--r-pill)] bg-[color-mix(in_srgb,var(--success)_14%,transparent)] px-2 py-0.5 text-[0.6rem] font-semibold uppercase tracking-wide text-[var(--success)]"
        >
          <BadgeCheck className="h-3 w-3" />
          Price confirmed
        </span>
      ) : (
        option.price_amount != null && (
          <span
            title="Not confirmed by a booking API — treat as indicative"
            className="rounded-[var(--r-pill)] bg-[color-mix(in_srgb,var(--muted)_12%,transparent)] px-2 py-0.5 text-[0.6rem] font-medium uppercase tracking-wide text-[var(--muted)]"
          >
            Indicative
          </span>
        )
      )}

      {option.bookable && (
        <span className="rounded-[var(--r-pill)] bg-[color-mix(in_srgb,var(--brand-400)_16%,transparent)] px-2 py-0.5 text-[0.6rem] font-semibold uppercase tracking-wide text-[var(--brand-500)]">
          Bookable
        </span>
      )}

      {option.source_url && (
        <a
          href={option.source_url}
          target="_blank"
          rel="noreferrer noopener"
          className="inline-flex items-center gap-1 text-[0.6rem] font-medium text-[var(--brand-500)] hover:underline"
          title={option.source_url}
        >
          <ExternalLink className="h-3 w-3" />
          View source
        </a>
      )}

      {option.last_checked && (
        <span className="text-[0.6rem] text-[var(--muted)]">
          checked {option.last_checked}
        </span>
      )}
    </div>
  );
}

/** Compact status pill used by the Vault and Engine pages. */
export function StatusPill({
  status,
  detail,
  className,
}: {
  status: string;
  detail?: string | null;
  className?: string;
}) {
  const TONES: Record<string, string> = {
    healthy: "text-[var(--success)] bg-[color-mix(in_srgb,var(--success)_14%,transparent)]",
    rate_limited:
      "text-[var(--warning)] bg-[color-mix(in_srgb,var(--warning)_16%,transparent)]",
    limit_reached:
      "text-[var(--warning)] bg-[color-mix(in_srgb,var(--warning)_16%,transparent)]",
    invalid: "text-[var(--danger)] bg-[color-mix(in_srgb,var(--danger)_14%,transparent)]",
    disabled: "text-[var(--muted)] bg-[color-mix(in_srgb,var(--muted)_12%,transparent)]",
    untested: "text-[var(--muted)] bg-[color-mix(in_srgb,var(--muted)_12%,transparent)]",
  };
  const LABELS: Record<string, string> = {
    healthy: "Healthy",
    rate_limited: "Rate limited",
    limit_reached: "Limit reached",
    invalid: "Invalid",
    disabled: "Disabled",
    untested: "Untested",
  };

  return (
    <span
      title={detail ?? undefined}
      className={cn(
        "inline-flex shrink-0 items-center gap-1 rounded-[var(--r-pill)] px-2 py-0.5",
        "text-[0.65rem] font-semibold",
        TONES[status] ?? TONES.untested,
        className,
      )}
    >
      <span className="h-1.5 w-1.5 rounded-full bg-current" />
      {LABELS[status] ?? status}
    </span>
  );
}
